export const chaters = [
  {
    text: "BASH 基本语法",
    collapsed: false,
    items: [
      { text: '简介', link: '/bash/intro.html' },
      { text: '基本语法', link: '/bash/grammar.html' },
      { text: '模式扩展', link: '/bash/expansion.html' },
      { text: '引号和转义', link: '/bash/quotation.html' },
      { text: '变量', link: '/bash/variable.html' },
      { text: '字符串操作', link: '/bash/string.html' },
      { text: '算术运算', link: '/bash/arithmetic.html' },
      { text: '行操作', link: '/bash/readline.html' },
      { text: '目录堆栈', link: '/bash/stack.html' },
      { text: '脚本入门', link: '/bash/script.html' },
      { text: 'read 命令', link: '/bash/read.html' },
      { text: '条件判断', link: '/bash/condition.html' },
      { text: '循环', link: '/bash/loop.html' },
      { text: '函数', link: '/bash/function.html' },
      { text: '数组', link: '/bash/array.html' },
      { text: 'set 命令，shopt 命令', link: '/bash/set.html' },
      { text: '脚本除错', link: '/bash/debug.html' },
      { text: 'mktemp 命令，trap 命令', link: '/bash/mktemp.html' },
      { text: '启动环境', link: '/bash/startup.html' },
      { text: '命令提示符', link: '/bash/prompt.html' },
    ],
  },
  {
    text: "计算机管理",
    collapsed: false,
    items: [
      { text: '归档和备份', link: '/bash/archives/archiving.html' },
      { text: '异步任务', link: '/bash/archives/async.html' },
      { text: 'Shell 的命令', link: '/bash/archives/command.html' },
      { text: '文件操作', link: '/bash/archives/file-operation.html' },
      { text: '文件系统', link: '/bash/archives/file.html' },
      { text: '硬件操作', link: '/bash/archives/hardware.html' },
      { text: '主机管理', link: '/bash/archives/host.html' },
      { text: '命名管道', link: '/bash/archives/named-pipe.html' },
      { text: '进程管理', link: '/bash/archives/process.html' },
      { text: '重定向', link: '/bash/archives/redirection.html' },
      { text: '正则表达式', link: '/bash/archives/regex.html' },
      { text: '系统信息', link: '/bash/archives/system.html' },
      { text: '文本处理', link: '/bash/archives/text.html' },
      { text: '时间管理', link: '/bash/archives/time.html' },
      { text: '用户管理', link: '/bash/archives/user.html' },
    ]
  }
]
