export const chaters = [
  {
    text: "文本处理",
    collapsed: false,
    items: [
      { text: "awk", link: "/bash/archives/commands/awk.html" },
      { text: "cut", link: "/bash/archives/commands/cut.html" },
      { text: "sed", link: "/bash/archives/commands/sed.html" },
      { text: "grep", link: "/bash/archives/commands/grep.html" },
      { text: "find", link: "/bash/archives/commands/find.html" },
      { text: "ps", link: "/bash/archives/commands/ps.html" },
      { text: "scp", link: "/bash/archives/commands/scp.html" },
      { text: "xargs", link: "/bash/archives/commands/xargs.html" },
      { text: "截取内容", link: "/bash/advanced-example.md" },
    ],
  },
  {
    text: "基本命令",
    collapsed: false,
    items: [
      { text: "alias", link: "/bash/archives/commands/alias.html" },
      { text: "awk", link: "/bash/archives/commands/awk.html" },
      { text: "cal", link: "/bash/archives/commands/cal.html" },
      { text: "cat", link: "/bash/archives/commands/cat.html" },
      { text: "clear", link: "/bash/archives/commands/clear.html" },
      { text: "cp", link: "/bash/archives/commands/cp.html" },
      { text: "cut", link: "/bash/archives/commands/cut.html" },
      { text: "date", link: "/bash/archives/commands/date.html" },
      { text: "dd", link: "/bash/archives/commands/dd.html" },
      { text: "df", link: "/bash/archives/commands/df.html" },
      { text: "du", link: "/bash/archives/commands/du.html" },
      { text: "egrep", link: "/bash/archives/commands/egrep.html" },
      { text: "export", link: "/bash/archives/commands/export.html" },
      { text: "file", link: "/bash/archives/commands/file.html" },
      { text: "find", link: "/bash/archives/commands/find.html" },
      { text: "fmt", link: "/bash/archives/commands/fmt.html" },
      { text: "grep", link: "/bash/archives/commands/grep.html" },
      { text: "gunzip", link: "/bash/archives/commands/gunzip.html" },
      { text: "gzcat", link: "/bash/archives/commands/gzcat.html" },
      { text: "gzip", link: "/bash/archives/commands/gzip.html" },
      { text: "kill", link: "/bash/archives/commands/kill.html" },
      { text: "killall", link: "/bash/archives/commands/killall.html" },
      { text: "last", link: "/bash/archives/commands/last.html" },
      { text: "lpq", link: "/bash/archives/commands/lpq.html" },
      { text: "lpr", link: "/bash/archives/commands/lpr.html" },
      { text: "ls", link: "/bash/archives/commands/ls.html" },
      { text: "nl", link: "/bash/archives/commands/nl.html" },
      { text: "ps", link: "/bash/archives/commands/ps.html" },
      { text: "scp", link: "/bash/archives/commands/scp.html" },
      { text: "sed", link: "/bash/archives/commands/sed.html" },
      { text: "sort", link: "/bash/archives/commands/sort.html" },
      { text: "tr", link: "/bash/archives/commands/tr.html" },
      { text: "uname", link: "/bash/archives/commands/uname.html" },
      { text: "uniq", link: "/bash/archives/commands/uniq.html" },
      { text: "uptime", link: "/bash/archives/commands/uptime.html" },
      { text: "w", link: "/bash/archives/commands/w.html" },
      { text: "wc", link: "/bash/archives/commands/wc.html" },
      { text: "whereis", link: "/bash/archives/commands/whereis.html" },
      { text: "which", link: "/bash/archives/commands/which.html" },
      { text: "who", link: "/bash/archives/commands/who.html" },
    ],
  },
];
