export const chaters = [
  {
    text: "入门篇",
    collapsed: false,
    items: [
      { text: "导论", link: "/js/basic/introduction.html" },
      { text: "历史", link: "/js/basic/history.html" },
      { text: "基本语法", link: "/js/basic/grammar.html" },
    ],
  },
  {
    text: "数据类型",
    collapsed: false,
    items: [
      { text: "概述", link: "/js/types/general.html" },
      {
        text: "null，undefined 和布尔值",
        link: "/js/types/null-undefined-boolean.html",
      },
      { text: "数值", link: "/js/types/number.html" },
      { text: "字符串", link: "/js/types/string.html" },
      { text: "对象", link: "/js/types/object.html" },
      { text: "函数", link: "/js/types/function.html" },
      { text: "数组", link: "/js/types/array.html" },
    ],
  },
  {
    text: "运算符",
    collapsed: false,
    items: [
      { text: "算术运算符", link: "/js/operators/arithmetic.html" },
      { text: "比较运算符", link: "/js/operators/comparison.html" },
      { text: "布尔运算符", link: "/js/operators/boolean.html" },
      { text: "二进制位运算符", link: "/js/operators/bit.html" },
      { text: "其他运算符，运算顺序", link: "/js/operators/priority.html" },
    ],
  },
  {
    text: "语法专题",
    collapsed: false,
    items: [
      { text: "数据类型的转换", link: "/js/features/conversion.html" },
      { text: "错误处理机制", link: "/js/features/error.html" },
      { text: "编程风格", link: "/js/features/style.html" },
      { text: "console 对象与控制台", link: "/js/features/console.html" },
    ],
  },
  {
    text: "标准库",
    collapsed: false,
    items: [
      { text: "Object 对象", link: "/js/stdlib/object.html" },
      { text: "属性描述对象", link: "/js/stdlib/attributes.html" },
      { text: "Array 对象", link: "/js/stdlib/array.html" },
      { text: "包装对象", link: "/js/stdlib/wrapper.html" },
      { text: "Boolean 对象", link: "/js/stdlib/boolean.html" },
      { text: "Number 对象", link: "/js/stdlib/number.html" },
      { text: "String 对象", link: "/js/stdlib/string.html" },
      { text: "Math 对象", link: "/js/stdlib/math.html" },
      { text: "Date 对象", link: "/js/stdlib/date.html" },
      { text: "RegExp 对象", link: "/js/stdlib/regexp.html" },
      { text: "JSON 对象", link: "/js/stdlib/json.html" },
    ],
  },
  {
    text: "面向对象编程",
    collapsed: false,
    items: [
      { text: "实例对象与 new 命令", link: "/js/oop/new.html" },
      { text: "this 关键字", link: "/js/oop/this.html" },
      { text: "对象的继承", link: "/js/oop/prototype.html" },
      { text: "Object 对象的相关方法", link: "/js/oop/object.html" },
      { text: "严格模式", link: "/js/oop/strict.html" },
    ],
  },

  {
    text: "异步操作",
    collapsed: false,
    items: [
      { text: "概述", link: "/js/async/general.html" },
      { text: "定时器", link: "/js/async/timer.html" },
      { text: "Promise 对象", link: "/js/async/promise.html" },
    ],
  },
  {
    text: "DOM",
    collapsed: false,
    items: [
      { text: "概述", link: "/js/dom/general.html" },
      { text: "Node 接口", link: "/js/dom/node.html" },
      {
        text: "NodeList 接口，HTMLCollection 接口",
        link: "/js/dom/nodelist.html",
      },
      {
        text: "ParentNode 接口，ChildNode 接口",
        link: "/js/dom/parentnode.html",
      },
      { text: "Document 节点", link: "/js/dom/document.html" },
      { text: "Element 节点", link: "/js/dom/element.html" },
      { text: "属性的操作", link: "/js/dom/attributes.html" },
      { text: "Text 节点和 DocumentFragment 节点", link: "/js/dom/text.html" },
      { text: "CSS 操作", link: "/js/dom/css.html" },
      { text: "Mutation Observer API", link: "/js/dom/mutationobserver.html" },
    ],
  },
  {
    text: "事件",
    collapsed: false,
    items: [
      { text: "EventTarget 接口", link: "/js/events/eventtarget.html" },
      { text: "事件模型", link: "/js/events/model.html" },
      { text: "Event 对象", link: "/js/events/event.html" },
      { text: "鼠标事件", link: "/js/events/mouse.html" },
      { text: "键盘事件", link: "/js/events/keyboard.html" },
      { text: "进度事件", link: "/js/events/progress.html" },
      { text: "表单事件", link: "/js/events/form.html" },
      { text: "触摸事件", link: "/js/events/touch.html" },
      { text: "拖拉事件", link: "/js/events/drag.html" },
      { text: "其他常见事件", link: "/js/events/common.html" },
      {
        text: "GlobalEventHandlers 接口",
        link: "/js/events/globaleventhandlers.html",
      },
    ],
  },
  {
    text: "浏览器模型",
    collapsed: false,
    items: [
      { text: "浏览器模型概述", link: "/js/bom/engine.html" },
      { text: "window 对象", link: "/js/bom/window.html" },
      { text: "Navigator 对象，Screen 对象", link: "/js/bom/navigator.html" },
      { text: "Cookie", link: "/js/bom/cookie.html" },
      { text: "XMLHttpRequest 对象", link: "/js/bom/xmlhttprequest.html" },
      { text: "同源限制", link: "/js/bom/same-origin.html" },
      { text: "CORS 通信", link: "/js/bom/cors.html" },
      { text: "Storage 接口", link: "/js/bom/storage.html" },
      { text: "History 对象", link: "/js/bom/history.html" },
      {
        text: "Location 对象，URL 对象，URLSearchParams 对象",
        link: "/js/bom/location.html",
      },
      { text: "ArrayBuffer 对象，Blob 对象", link: "/js/bom/arraybuffer.html" },
      {
        text: "File 对象，FileList 对象，FileReader 对象",
        link: "/js/bom/file.html",
      },
      { text: "表单，FormData 对象", link: "/js/bom/form.html" },
      { text: "IndexedDB API", link: "/js/bom/indexeddb.html" },
      { text: "Web Worker", link: "/js/bom/webworker.html" },
    ],
  },
  {
    text: "附录：网页元素接口",
    collapsed: false,
    items: [
      { text: "&lt;a&gt;", link: "/js/elements/a.html" },
      { text: "&lt;img&gt;", link: "/js/elements/image.html" },
      { text: "&lt;form&gt;", link: "/js/elements/form.html" },
      { text: "&lt;input&gt;", link: "/js/elements/input.html" },
      { text: "&lt;button&gt;", link: "/js/elements/button.html" },
      { text: "&lt;option&gt;", link: "/js/elements/option.html" },
      { text: "&lt;video&gt;，&lt;audio&gt;", link: "/js/elements/video.html" },
    ],
  },
];
