export const chaters = [
  { text: "1.SVG教程", link: "/svg/1.SVG教程.html" },
  { text: "2.SVG示例", link: "/svg/2.SVG示例.html" },
  { text: "3.一个简单的SVG示例", link: "/svg/3.一个简单的SVG示例.html" },
  { text: "4.在Web浏览器中显示SVG", link: "/svg/4.在Web浏览器中显示SVG.html" },
  { text: "5.SVG图标", link: "/svg/5.SVG图标.html" },
  { text: "6.SVG坐标系", link: "/svg/6.SVG坐标系.html" },
  { text: "7.SVG svg元素", link: "/svg/7.SVG svg元素.html" },
  { text: "8.SVG g元素", link: "/svg/8.SVG g元素.html" },
  { text: "9.SVG rect元素", link: "/svg/9.SVG rect元素.html" },
  { text: "10.SVG circle元素", link: "/svg/10.SVG circle元素.html" },
  { text: "11.SVG ellipse元素", link: "/svg/11.SVG ellipse元素.html" },
  { text: "12.SVG line元素", link: "/svg/12.SVG line元素.html" },
  { text: "13.SVG polyline元素", link: "/svg/13.SVG polyline元素.html" },
  { text: "14.SVG polygon元素", link: "/svg/14.SVG polygon元素.html" },
  { text: "15.SVG path元素", link: "/svg/15.SVG path元素.html" },
  { text: "16.SVG marker元素", link: "/svg/16.SVG marker元素.html" },
  { text: "17.SVG text元素", link: "/svg/17.SVG text元素.html" },
  { text: "18.SVG tspan元素", link: "/svg/18.SVG tspan元素.html" },
  { text: "19.SVG tref元素", link: "/svg/19.SVG tref元素.html" },
  { text: "20.SVG textpath元素", link: "/svg/20.SVG textpath元素.html" },
  { text: "21.SVG switch元素", link: "/svg/21.SVG switch元素.html" },
  { text: "22.SVG image元素", link: "/svg/22.SVG image元素.html" },
  { text: "23.SVG a元素", link: "/svg/23.SVG a元素.html" },
  { text: "24.SVG defs元素", link: "/svg/24.SVG defs元素.html" },
  { text: "25.SVG symbol元素", link: "/svg/25.SVG symbol元素.html" },
  { text: "26.SVG use元素", link: "/svg/26.SVG use元素.html" },
  { text: "27.SVG和CSS-级联样式表", link: "/svg/27.SVG和CSS-级联样式表.html" },
  { text: "28.SVG轮廓", link: "/svg/28.SVG轮廓.html" },
  { text: "29.SVG填充", link: "/svg/29.SVG填充.html" },
  { text: "30.SVG视口和视图框", link: "/svg/30.SVG视口和视图框.html" },
  { text: "31.SVG动画", link: "/svg/31.SVG动画.html" },
  { text: "32.SVG脚本", link: "/svg/32.SVG脚本.html" },
  { text: "33.SVG变换", link: "/svg/33.SVG变换.html" },
  { text: "34.SVG渐变", link: "/svg/34.SVG渐变.html" },
  { text: "35.SVG填充图案", link: "/svg/35.SVG填充图案.html" },
  { text: "36.SVG剪裁路径", link: "/svg/36.SVG剪裁路径.html" },
  { text: "37.SVG遮罩", link: "/svg/37.SVG遮罩.html" },
  { text: "38.SVG滤镜", link: "/svg/38.SVG滤镜.html" }
]
